vector_add.c instrucciones:
gcc -g -Wall -o vector_add vector_add.c
./vector_add

mpi_vector_add.c instrucciones:
mpicc -g -Wall -o mpi_vector_add mpi_vector_add.c
mpiexec -n <comm_sz> ./mpi_vector_add

mpi_vector_add_productpunt.c instrucciones:
mpicc -g -Wall -o mpi_vector_add_dot_product mpi_vector_add_dot_product.c
mpiexec -n <comm_sz> ./mpi_vector_add_dot_product